-- Tabla: extension
-- Crea una tabla para gestionar ofertas de extensión con RLS habilitado.

create table if not exists public.extension (
    id bigint generated by default as identity primary key,
    nombre text not null,
    modalidad text not null
        check (modalidad in ('virtual', 'hibrida', 'presencial')),
    carga_horaria integer not null check (carga_horaria > 0),
    duration integer not null check (duration > 0),
    descripcion text not null,
    objetivo text not null,
    precio numeric(10, 2) not null default 0 check (precio >= 0),
    tipo text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.extension is
    'Oferta de extensión universitaria (cursos, talleres, diplomaturas, etc.).';

comment on column public.extension.modalidad is
    'Modalidad de cursado: virtual, hibrida o presencial.';

-- Permisos base para API roles
grant select on public.extension to anon, authenticated;
grant insert, update, delete on public.extension to authenticated;
grant usage, select on sequence public.extension_id_seq to authenticated;

-- Row Level Security
alter table public.extension enable row level security;

-- Limpiar políticas si ya existen (idempotencia)
drop policy if exists "extension_select_public" on public.extension;
drop policy if exists "extension_insert_authenticated" on public.extension;
drop policy if exists "extension_update_authenticated" on public.extension;
drop policy if exists "extension_delete_authenticated" on public.extension;

-- Cualquier usuario (incluido anon) puede visualizar
create policy "extension_select_public"
on public.extension
for select
to public
using (true);

-- Solo autenticados pueden gestionar (insert/update/delete)
create policy "extension_insert_authenticated"
on public.extension
for insert
to authenticated
with check (true);

create policy "extension_update_authenticated"
on public.extension
for update
to authenticated
using (true)
with check (true);

create policy "extension_delete_authenticated"
on public.extension
for delete
to authenticated
using (true);
